"use client"

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import {
  ArrowLeft,
  Heart,
  AlertTriangle,
  ShieldAlert,
  ShieldCheck,
  Info,
  Stethoscope,
  GraduationCap,
  BookOpen,
  FileWarning,
} from "lucide-react"

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background relative">
      {/* Navigation */}
      <nav className="border-b border-border bg-card/50 backdrop-blur-sm sticky top-0 z-50 opacity-0 animate-fade-in-down fill-mode-forwards">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-4 opacity-0 animate-fade-in-left animation-delay-200 fill-mode-forwards">
              <Link href="/" className="flex items-center space-x-2 hover:opacity-80 transition-opacity">
                <ArrowLeft className="h-5 w-5" />
                <span>Back to Home</span>
              </Link>
            </div>
            <div className="flex items-center space-x-2 opacity-0 animate-fade-in-right animation-delay-300 fill-mode-forwards">
              <div className="p-2 bg-primary/10 rounded-lg">
                <Heart className="h-6 w-6 text-primary animate-pulse" />
              </div>
              <span className="text-xl font-bold font-manrope">MedRisk AI</span>
            </div>
          </div>
        </div>
      </nav>

      {/* Header */}
      <div className="bg-gradient-to-b from-primary/5 to-background py-16 relative">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="flex justify-center mb-6 opacity-0 animate-fade-in-up animation-delay-400 fill-mode-forwards">
            <div className="p-4 bg-primary/10 rounded-full">
              <ShieldAlert className="h-8 w-8 text-primary" />
            </div>
          </div>
          <h1 className="text-4xl font-bold font-manrope mb-4 opacity-0 animate-fade-in-up animation-delay-500 fill-mode-forwards">
            Disclaimer
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto text-pretty opacity-0 animate-fade-in-up animation-delay-600 fill-mode-forwards">
            Please read this disclaimer carefully before using MedRisk AI
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="space-y-8">
          {/* Medical Disclaimer */}
          <Card className="shadow-xl border-border bg-card opacity-0 animate-fade-in-up animation-delay-700 fill-mode-forwards">
            <CardHeader>
              <CardTitle className="flex items-center gap-3">
                <div className="p-2 bg-primary/10 rounded-lg">
                  <Stethoscope className="h-5 w-5 text-primary" />
                </div>
                Medical Disclaimer
              </CardTitle>
              <CardDescription>
                MedRisk AI is not a medical device, does not provide medical advice, and is not a substitute for professional medical care.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed">
              <p>
                MedRisk AI is an experimental machine learning demonstration built for educational and research purposes
                only. The predictions, risk levels, and assessments generated by this platform are simulated and must
                never be used to make real medical decisions.
              </p>
              <p>
                The tool does not have knowledge of a patient's full medical history, current medications, allergies,
                genetic factors, or any other context a qualified healthcare provider would consider. As a result, the
                output may be incomplete, misleading, or simply wrong.
              </p>
              <div className="flex items-start gap-3 p-4 rounded-lg bg-red-500/10 border border-red-500/20">
                <AlertTriangle className="h-5 w-5 text-red-400 shrink-0 mt-0.5" />
                <p className="text-foreground">
                  <span className="font-semibold text-red-400">Important:</span> Never rely on this tool in an
                  emergency. If you or someone else is experiencing a medical emergency, call your local emergency
                  services immediately.
                </p>
              </div>
            </CardContent>
          </Card>

          {/* AI Accuracy */}
          <Card className="shadow-xl border-border bg-card opacity-0 animate-fade-in-up animation-delay-800 fill-mode-forwards">
            <CardHeader>
              <CardTitle className="flex items-center gap-3">
                <div className="p-2 bg-secondary/10 rounded-lg">
                  <Info className="h-5 w-5 text-secondary" />
                </div>
                AI May Make Mistakes
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed">
              <p>
                The risk assessment model is trained on a limited, curated dataset and cannot match the judgment of a
                trained clinician. Even when the model is highly confident, its conclusion can be incorrect.
              </p>
              <ul className="space-y-2">
                <li className="flex items-start gap-2">
                  <FileWarning className="h-4 w-4 text-secondary shrink-0 mt-0.5" />
                  <span>Treat every result as a hypothesis, not a diagnosis.</span>
                </li>
                <li className="flex items-start gap-2">
                  <FileWarning className="h-4 w-4 text-secondary shrink-0 mt-0.5" />
                  <span>Do not use the output to decide on treatment, medication, or hospitalization.</span>
                </li>
                <li className="flex items-start gap-2">
                  <FileWarning className="h-4 w-4 text-secondary shrink-0 mt-0.5" />
                  <span>Always verify any finding with a qualified healthcare professional.</span>
                </li>
              </ul>
            </CardContent>
          </Card>

          {/* Always Consult a Doctor */}
          <Card className="shadow-xl border-border bg-card opacity-0 animate-fade-in-up animation-delay-900 fill-mode-forwards">
            <CardHeader>
              <CardTitle className="flex items-center gap-3">
                <div className="p-2 bg-primary/10 rounded-lg">
                  <ShieldCheck className="h-5 w-5 text-primary" />
                </div>
                Always Consult a Doctor
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed">
              <p>
                For any health concern, symptom, or medical question, consult a qualified healthcare professional. Your
                doctor considers your full medical history, lifestyle, and clinical context — something no AI model on
                this platform can do.
              </p>
              <p>
                Health decisions should be made in partnership with licensed medical providers. Never delay or disregard
                professional medical advice because of something this tool told you.
              </p>
            </CardContent>
          </Card>

          {/* Educational Purpose */}
          <Card className="shadow-xl border-border bg-card opacity-0 animate-fade-in-up animation-delay-1000 fill-mode-forwards">
            <CardHeader>
              <CardTitle className="flex items-center gap-3">
                <div className="p-2 bg-secondary/10 rounded-lg">
                  <GraduationCap className="h-5 w-5 text-secondary" />
                </div>
                Educational & Research Use Only
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed">
              <p>
                This platform is intended for students, researchers, developers, and curious minds exploring AI in
                healthcare. It is a learning tool that demonstrates machine learning concepts applied to clinical-style
                data — not a clinical product.
              </p>
              <ul className="space-y-2">
                <li className="flex items-start gap-2">
                  <BookOpen className="h-4 w-4 text-secondary shrink-0 mt-0.5" />
                  <span>Explore how patient vital signs relate to risk levels.</span>
                </li>
                <li className="flex items-start gap-2">
                  <BookOpen className="h-4 w-4 text-secondary shrink-0 mt-0.5" />
                  <span>Understand the strengths and limits of predictive models.</span>
                </li>
                <li className="flex items-start gap-2">
                  <BookOpen className="h-4 w-4 text-secondary shrink-0 mt-0.5" />
                  <span>Learn why human clinical judgment remains irreplaceable.</span>
                </li>
              </ul>
            </CardContent>
          </Card>

          {/* No Liability */}
          <Card className="shadow-xl border-border bg-card opacity-0 animate-fade-in-up animation-delay-1100 fill-mode-forwards">
            <CardHeader>
              <CardTitle className="flex items-center gap-3">
                <div className="p-2 bg-primary/10 rounded-lg">
                  <ShieldAlert className="h-5 w-5 text-primary" />
                </div>
                No Liability
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground leading-relaxed">
              <p>
                MedRisk AI and its contributors provide this software "as is" without warranties of any kind,
                express or implied. To the fullest extent permitted by law, we are not liable for any damages or harm
                arising from the use of, or reliance on, the predictions or information provided by this platform.
              </p>
              <p>
                By using this tool, you acknowledge that you understand its limitations and accept full responsibility
                for how you use its output.
              </p>
            </CardContent>
          </Card>

          {/* CTA */}
          <div className="text-center pt-4 opacity-0 animate-fade-in-up animation-delay-1200 fill-mode-forwards">
            <Link href="/assessment">
              <Button
                size="lg"
                className="bg-primary hover:bg-primary/90 text-lg px-8 py-6 group hover:scale-105 transition-all duration-300 shadow-lg hover:shadow-primary/25"
              >
                <Stethoscope className="mr-2 h-5 w-5 group-hover:scale-110 transition-transform" />
                Return to Assessment
              </Button>
            </Link>
            <div className="mt-4">
              <Link href="/" className="text-sm text-muted-foreground hover:text-primary transition-colors duration-200">
                <ArrowLeft className="inline h-4 w-4 mr-1 -mt-0.5" />
                Back to Home
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-card/50 border-t border-border py-12 animate-fade-in-up">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-3 gap-8">
            <div className="space-y-4 col-span-1">
              <div className="flex items-center space-x-2 group">
                <div className="p-2 bg-primary/10 rounded-lg group-hover:bg-primary/20 transition-colors duration-300">
                  <Heart className="h-5 w-5 text-primary group-hover:animate-pulse" />
                </div>
                <span className="text-lg font-bold font-manrope">MedRisk AI</span>
              </div>
              <p className="text-sm text-muted-foreground">
                Advanced AI-powered health risk assessment platform for healthcare professionals.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-4">Platform</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>
                  <Link
                    href="/assessment"
                    className="hover:text-foreground transition-colors duration-200 hover:translate-x-1 inline-block"
                  >
                    Risk Assessment
                  </Link>
                </li>
                <li>
                  <Link
                    href="/"
                    className="hover:text-foreground transition-colors duration-200 hover:translate-x-1 inline-block"
                  >
                    Home
                  </Link>
                </li>
                <li>
                  <Link
                    href="/#why-choose"
                    className="hover:text-foreground transition-colors duration-200 hover:translate-x-1 inline-block"
                  >
                    Why MedRisk AI
                  </Link>
                </li>
              </ul>
            </div>

            <div>
              <h3 className="font-semibold mb-4">Resources</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>
                  <Link
                    href="https://armaan-ai.vercel.app"
                    target="_blank"
                    className="hover:text-foreground transition-colors duration-200 hover:translate-x-1 inline-block"
                  >
                    Developer Portfolio
                  </Link>
                </li>
                <li>
                  <Link
                    href="https://github.com/ItsMeArm00n/med-risk-ai"
                    target="_blank"
                    className="hover:text-foreground transition-colors duration-200 hover:translate-x-1 inline-block"
                  >
                    Website Source (GitHub)
                  </Link>
                </li>
                <li>
                  <Link
                    href="/disclaimer"
                    className="hover:text-foreground transition-colors duration-200 hover:translate-x-1 inline-block"
                  >
                    Disclaimer
                  </Link>
                </li>
              </ul>
            </div>
          </div>

          <div className="border-t border-border mt-12 pt-8">
            <div className="flex flex-col md:flex-row md:justify-between items-center gap-4">
              <div className="text-left">
                <p className="text-sm text-muted-foreground">
                  Medical Disclaimer: This tool is for educational and research purposes only. Always consult qualified
                  healthcare professionals for medical decisions.{" "}
                  <Link
                    href="/disclaimer"
                    className="text-primary hover:text-primary/80 underline underline-offset-4 transition-colors duration-200"
                  >
                    Read full disclaimer
                  </Link>
                </p>
                <p className="text-xs text-muted-foreground mt-2">
                  © 2025 MedRisk AI. Advancing healthcare insights through open-source machine learning.
                </p>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-sm text-muted-foreground">Built by Armaan Kumar</span>
                <Link
                  href="https://armaan-ai.vercel.app"
                  target="_blank"
                  className="text-sm px-4 py-2 bg-primary/10 hover:bg-primary/20 text-primary rounded-md transition-colors"
                >
                  Portfolio
                </Link>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
